## linkbar links
---
- href: '/'
  text: <i class="fas fa-home"></i> Home
- href: /who
  text: <i class="far fa-question-circle"></i> Who am I
- href: /calendar
  text: <i class="fas fa-calendar"></i> Calendar
- href: /contact
  text: <i class="fas fa-address-card"></i> Contacts
