---
menu:
items:
  - link: <i class="fas fa-home"></i><span class="show-for-sr">Back to home</span>
    href: /
    class: icon-link
    tipso: 
      position: bottom-right
      title: Back to home
  - link: <i class="fas fa-calendar-alt"></i> <span class="hide-for-medium">My calendar</span>
    href: /calendar
    class: icon-link
  - link: Contacts
    href: /contact
    class: icon-link
  - link: Who am I?
    href: /who
  - menu: Projects
    items:
    - separator: Current . . .
    - link: SPHPlayground
      href: http://playground.samiholck.com/
    - link: Raision Veneseura
      href: http://raisionvenseura.fi/
    - separator: . . . Past <i class="fas fa-skull fa-pull-right"></i>
    - link: Keijupäiväkodit
      href: /archive/keiju
    - link: Unikoris
      href: /archive/unikoris
    - link: DVD laboratorio
      href: /archive/dvdlabra
  - link: Intro
    href: /introduction.php
